### ISSUE TITLE
Where can I download the "mobilenet_v2.pth.tar"?

### ISSUE THREAD

**Issue by JerryDaHeLian** [TalentBoy2333/remote-sensing-image-caption#1]
About the "remote-sensing-image-caption/attention-model/model.py"
        mobilenet = MobileNetV2(n_class=1000)
        state_dict = torch.load('./models/mobilenet_v2.pth.tar', map_location='cpu')

Where can I download the "mobilenet_v2.pth.tar"?
I've been looking for it for a long time, but I can't find it. Can you help me?  Thanks！

**Comment by TalentBoy2333** [comment]
You can download it from this repo: https://github.com/tonylins/pytorch-mobilenet-v2

Sorry for the late reply
